spring:
  datasource:
    url: jdbc:h2:file:./data/eventhub;AUTO_SERVER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true

server:
  servlet:
    session:
      cookie:
        secure: false